### ISSUE TITLE
monit: Cannot connect to the monit daemon. Did you start it with http support?

### ISSUE THREAD

**Issue by khacluan** [engineyard/ey-cloud-recipes#285]
Us server error after we applied a changed configuration.
and this is custom log

```<application>``` instead of name of my application
```error
/usr/local/ey_resin/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require': iconv will be deprecated in the future, use String#encode instead.

================================================================================
Error executing action `run` on resource 'execute[restart-sidekiq-for-<application>]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of monit reload && sleep 1 && monit restart all -g <application>_sidekiq ----
STDOUT: 
STDERR: Reinitializing monit daemon
monit: Cannot connect to the monit daemon. Did you start it with http support?
monit: Cannot connect to the monit daemon. Did you start it with http support?
---- End output of monit reload && sleep 1 && monit restart all -g <application>_sidekiq ----
Ran monit reload && sleep 1 && monit restart all -g <application>_sidekiq returned 1

Resource Declaration:
---------------------
# In /etc/chef-custom/recipes/cookbooks/sidekiq/recipes/setup.rb

 22:     execute "restart-sidekiq-for-#{app_name}" do
 23:       command "monit reload && sleep 1 && monit restart all -g #{app_name}_sidekiq"
 24:       action :nothing
 25:     end
 26:     

Compiled Resource:
------------------
# Declared in /etc/chef-custom/recipes/cookbooks/sidekiq/recipes/setup.rb:22:in `block in from_file'

execute("restart-sidekiq-for-<application>") do
  action [:nothing]
  retries 0
  retry_delay 2
  command "monit reload && sleep 1 && monit restart all -g <application>_sidekiq"
  backup 5
  returns 0
  cookbook_name :sidekiq
  recipe_name "setup"
end

t reload]: /etc/chef-custom/recipes/cookbooks/elasticsearch/recipes/default.rb:164:in `from_file'
[2016-07-22T11:42:36+00:00] INFO: Processing remote_file[/tmp/phantomjs-1.9.2-linux-x86_64.tar.bz2] action create (phantomjs::default line 12)
[2016-07-22T11:42:36+00:00] INFO: Processing bash[unzip phantomjs] action run (phantomjs::default line 18)
[2016-07-22T11:42:36+00:00] INFO: Processing bash[copy phantomjs] action run (phantomjs::default line 25)
[2016-07-22T11:42:36+00:00] INFO: Processing template[/etc/monit.d/rpush_<application>.monitrc] action create (rpush::default line 7)
[2016-07-22T11:42:36+00:00] INFO: Processing remote_file[/data/<application>/shared/bin/rpush] action create (rpush::default line 17)
[2016-07-22T11:42:36+00:00] WARN: remote_file is deprecated for fetching files from cookbooks. Use cookbook_file instead
[2016-07-22T11:42:36+00:00] WARN: From remote_file[/data/<application>/shared/bin/rpush] on /etc/chef-custom/recipes/cookbooks/rpush/recipes/default.rb:17:in `block in from_file'
[2016-07-22T11:42:36+00:00] WARN: remote_file is deprecated for fetching files from cookbooks. Use cookbook_file instead
[2016-07-22T11:42:36+00:00] WARN: From remote_file[/data/<application>/shared/bin/rpush] on /etc/chef-custom/recipes/cookbooks/rpush/recipes/default.rb:17:in `block in from_file'
[2016-07-22T11:42:36+00:00] INFO: Processing execute[ensure-rpush-is-setup-with-monit] action run (rpush::default line 26)
[2016-07-22T11:42:36+00:00] INFO: execute[ensure-rpush-is-setup-with-monit] ran successfully
[2016-07-22T11:42:36+00:00] INFO: Processing execute[reload-monit] action nothing (sidekiq::cleanup line 7)
[2016-07-22T11:42:36+00:00] INFO: Processing execute[reporting for sidekiq] action run (sidekiq::cleanup line 3)
[2016-07-22T11:42:38+00:00] INFO: execute[reporting for sidekiq] ran successfully
[2016-07-22T11:42:38+00:00] INFO: Processing file[/etc/monit.d/sidekiq_<application>.monitrc] action delete (sidekiq::cleanup line 22)
[2016-07-22T11:42:38+00:00] INFO: file[/etc/monit.d/sidekiq_<application>.monitrc] backed up to /var/chef/backup/etc/monit.d/sidekiq_<application>.monitrc.chef-20160722114238
[2016-07-22T11:42:38+00:00] INFO: file[/etc/monit.d/sidekiq_<application>.monitrc] removed backup at /var/chef/backup/./etc/monit.d/sidekiq_<application>.monitrc.chef-20160707110233
[2016-07-22T11:42:38+00:00] INFO: file[/etc/monit.d/sidekiq_<application>.monitrc] deleted file at /etc/monit.d/sidekiq_<application>.monitrc
[2016-07-22T11:42:38+00:00] INFO: Processing file[/data/<application>/shared/config/sidekiq_0.yml] action delete (sidekiq::cleanup line 29)
[2016-07-22T11:42:38+00:00] INFO: file[/data/<application>/shared/config/sidekiq_0.yml] backed up to /var/chef/backup/data/<application>/shared/config/sidekiq_0.yml.chef-20160722114238
[2016-07-22T11:42:38+00:00] INFO: file[/data/<application>/shared/config/sidekiq_0.yml] removed backup at /var/chef/backup/./data/<application>/shared/config/sidekiq_0.yml.chef-20160707110233
[2016-07-22T11:42:38+00:00] INFO: file[/data/<application>/shared/config/sidekiq_0.yml] deleted file at /data/<application>/shared/config/sidekiq_0.yml
[2016-07-22T11:42:38+00:00] INFO: Processing file[/data/<application>/shared/config/sidekiq_1.yml] action delete (sidekiq::cleanup line 29)
[2016-07-22T11:42:38+00:00] INFO: file[/data/<application>/shared/config/sidekiq_1.yml] backed up to /var/chef/backup/data/<application>/shared/config/sidekiq_1.yml.chef-20160722114238
[2016-07-22T11:42:38+00:00] INFO: file[/data/<application>/shared/config/sidekiq_1.yml] removed backup at /var/chef/backup/./data/<application>/shared/config/sidekiq_1.yml.chef-20160707110233
[2016-07-22T11:42:38+00:00] INFO: file[/data/<application>/shared/config/sidekiq_1.yml] deleted file at /data/<application>/shared/config/sidekiq_1.yml
[2016-07-22T11:42:38+00:00] INFO: Processing file[/data/<application>/shared/config/sidekiq_2.yml] action delete (sidekiq::cleanup line 29)
[2016-07-22T11:42:38+00:00] INFO: file[/data/<application>/shared/config/sidekiq_2.yml] backed up to /var/chef/backup/data/<application>/shared/config/sidekiq_2.yml.chef-20160722114238
[2016-07-22T11:42:38+00:00] INFO: file[/data/<application>/shared/config/sidekiq_2.yml] removed backup at /var/chef/backup/./data/<application>/shared/config/sidekiq_2.yml.chef-20160707110233
[2016-07-22T11:42:38+00:00] INFO: file[/data/<application>/shared/config/sidekiq_2.yml] deleted file at /data/<application>/shared/config/sidekiq_2.yml
[2016-07-22T11:42:38+00:00] INFO: Processing file[/engineyard/bin/sidekiq] action delete (sidekiq::cleanup line 36)
[2016-07-22T11:42:38+00:00] INFO: file[/engineyard/bin/sidekiq] backed up to /var/chef/backup/engineyard/bin/sidekiq.chef-20160722114238
[2016-07-22T11:42:38+00:00] INFO: file[/engineyard/bin/sidekiq] removed backup at /var/chef/backup/./engineyard/bin/sidekiq.chef-20160707110233
[2016-07-22T11:42:38+00:00] INFO: file[/engineyard/bin/sidekiq] deleted file at /engineyard/bin/sidekiq
[2016-07-22T11:42:38+00:00] INFO: Processing execute[kill-sidekiq] action run (sidekiq::cleanup line 41)
[2016-07-22T11:42:38+00:00] INFO: execute[kill-sidekiq] ran successfully
[2016-07-22T11:42:38+00:00] INFO: Processing execute[reporting for sidekiq] action run (sidekiq::setup line 3)
[2016-07-22T11:42:39+00:00] INFO: execute[reporting for sidekiq] ran successfully
[2016-07-22T11:42:39+00:00] INFO: Processing remote_file[/engineyard/bin/sidekiq] action create (sidekiq::setup line 13)
[2016-07-22T11:42:39+00:00] WARN: remote_file is deprecated for fetching files from cookbooks. Use cookbook_file instead
[2016-07-22T11:42:39+00:00] WARN: From remote_file[/engineyard/bin/sidekiq] on /etc/chef-custom/recipes/cookbooks/sidekiq/recipes/setup.rb:13:in `from_file'
[2016-07-22T11:42:39+00:00] WARN: remote_file is deprecated for fetching files from cookbooks. Use cookbook_file instead
[2016-07-22T11:42:39+00:00] WARN: From remote_file[/engineyard/bin/sidekiq] on /etc/chef-custom/recipes/cookbooks/sidekiq/recipes/setup.rb:13:in `from_file'
[2016-07-22T11:42:39+00:00] INFO: remote_file[/engineyard/bin/sidekiq] mode changed to 755
[2016-07-22T11:42:39+00:00] INFO: remote_file[/engineyard/bin/sidekiq] created file /engineyard/bin/sidekiq
[2016-07-22T11:42:39+00:00] INFO: Processing execute[restart-sidekiq-for-<application>] action nothing (sidekiq::setup line 22)
[2016-07-22T11:42:39+00:00] INFO: Processing template[/etc/monit.d/sidekiq_<application>.monitrc] action create (sidekiq::setup line 28)
[2016-07-22T11:42:40+00:00] INFO: template[/etc/monit.d/sidekiq_<application>.monitrc] updated content
[2016-07-22T11:42:40+00:00] INFO: template[/etc/monit.d/sidekiq_<application>.monitrc] mode changed to 644
[2016-07-22T11:42:40+00:00] INFO: Processing execute[update-database-yml-pg-pool-for-<application>] action run (sidekiq::setup line 42)
[2016-07-22T11:42:40+00:00] INFO: execute[update-database-yml-pg-pool-for-<application>] ran successfully
[2016-07-22T11:42:40+00:00] INFO: execute[update-database-yml-pg-pool-for-<application>] not queuing delayed action run on execute[restart-sidekiq-for-<application>] (delayed), as it's already been queued
[2016-07-22T11:42:40+00:00] INFO: Processing template[/data/<application>/shared/config/sidekiq_0.yml] action create (sidekiq::setup line 52)
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_0.yml] updated content
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_0.yml] owner changed to 1000
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_0.yml] group changed to 1000
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_0.yml] mode changed to 644
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_0.yml] not queuing delayed action run on execute[restart-sidekiq-for-<application>] (delayed), as it's already been queued
[2016-07-22T11:42:40+00:00] INFO: Processing template[/data/<application>/shared/config/sidekiq_1.yml] action create (sidekiq::setup line 52)
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_1.yml] updated content
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_1.yml] owner changed to 1000
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_1.yml] group changed to 1000
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_1.yml] mode changed to 644
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_1.yml] not queuing delayed action run on execute[restart-sidekiq-for-<application>] (delayed), as it's already been queued
[2016-07-22T11:42:40+00:00] INFO: Processing template[/data/<application>/shared/config/sidekiq_2.yml] action create (sidekiq::setup line 52)
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_2.yml] updated content
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_2.yml] owner changed to 1000
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_2.yml] group changed to 1000
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_2.yml] mode changed to 644
[2016-07-22T11:42:40+00:00] INFO: template[/data/<application>/shared/config/sidekiq_2.yml] not queuing delayed action run on execute[restart-sidekiq-for-<application>] (delayed), as it's already been queued
[2016-07-22T11:42:40+00:00] INFO: Processing template[/data/<application>/shared/config/redis.yml] action create (redis-yml::default line 11)
[2016-07-22T11:42:40+00:00] INFO: Processing execute[remove-vm.overcommit_memory-in-sysctl] action run (redis::default line 7)
[2016-07-22T11:42:40+00:00] INFO: execute[remove-vm.overcommit_memory-in-sysctl] ran successfully
[2016-07-22T11:42:40+00:00] INFO: Processing file[add-vm.overcommit_memory-to-sysctl] action create (redis::default line 9)
[2016-07-22T11:42:40+00:00] INFO: Processing ruby_block[append-to-/etc/sysctl.conf (46caddf70cab055e6437aaa5167eafd1)] action create (redis::default line 29)
[2016-07-22T11:42:40+00:00] INFO: ruby_block[append-to-/etc/sysctl.conf (46caddf70cab055e6437aaa5167eafd1)] called
[2016-07-22T11:42:40+00:00] INFO: Processing execute[reload-sysctl] action run (redis::default line 18)
[2016-07-22T11:42:40+00:00] INFO: execute[reload-sysctl] ran successfully
[2016-07-22T11:42:40+00:00] INFO: Processing file[unmasking dev-db/redis-2.6.16] action create (redis::default line 9)
[2016-07-22T11:42:40+00:00] INFO: Processing ruby_block[append-to-/etc/portage/package.keywords/local (8a63e5ed57e56c6ae77adde6c3b783c2)] action create (redis::default line 29)
[2016-07-22T11:42:40+00:00] INFO: Processing file[overriding hard mask for dev-db/redis-2.6.16] action create (redis::default line 9)
[2016-07-22T11:42:40+00:00] INFO: Processing ruby_block[append-to-/etc/portage/package.unmask/engineyard_overrides (8a63e5ed57e56c6ae77adde6c3b783c2)] action create (redis::default line 29)
[2016-07-22T11:42:40+00:00] INFO: Processing package[dev-db/redis] action upgrade (redis::default line 19)
[2016-07-22T11:42:43+00:00] INFO: Processing directory[/data/redis] action create (redis::default line 24)
[2016-07-22T11:42:43+00:00] INFO: Processing template[/etc/redis_util.conf] action create (redis::default line 32)
[2016-07-22T11:42:43+00:00] INFO: Processing template[/data/monit.d/redis_util.monitrc] action create (redis::default line 60)
[2016-07-22T11:42:43+00:00] INFO: Processing execute[monit reload] action run (redis::default line 75)
[2016-07-22T11:42:43+00:00] INFO: execute[monit reload] ran successfully
[2016-07-22T11:42:43+00:00] INFO: Processing execute[Remove existing redis_instance mapping from /etc/hosts] action run (redis::default line 89)
[2016-07-22T11:42:43+00:00] INFO: execute[Remove existing redis_instance mapping from /etc/hosts] ran successfully
[2016-07-22T11:42:43+00:00] INFO: Processing execute[Add redis_instance mapping to /etc/hosts] action run (redis::default line 94)
[2016-07-22T11:42:43+00:00] INFO: execute[Add redis_instance mapping to /etc/hosts] ran successfully
[2016-07-22T11:42:43+00:00] INFO: Processing remote_file[/tmp/elasticsearch-1.4.4.zip] action create (elasticsearch::default line 25)
[2016-07-22T11:42:43+00:00] INFO: Processing user[elasticsearch] action create (elasticsearch::default line 32)
[2016-07-22T11:42:43+00:00] INFO: Processing file[unmasking dev-java/icedtea-bin-7.2.3.3-r1] action create (elasticsearch::default line 9)
[2016-07-22T11:42:43+00:00] INFO: Processing ruby_block[append-to-/etc/portage/package.keywords/local (05334d3ea4843d74f5a0c4558399e631)] action create (elasticsearch::default line 29)
[2016-07-22T11:42:43+00:00] INFO: Processing package[dev-java/icedtea-bin] action upgrade (elasticsearch::default line 45)
[2016-07-22T11:43:30+00:00] INFO: package[dev-java/icedtea-bin] upgraded from uninstalled to 7.2.3.3-r1
[2016-07-22T11:43:30+00:00] INFO: Processing execute[Set the default Java version to 7.2.3.3-r1] action run (elasticsearch::default line 50)
[2016-07-22T11:43:30+00:00] INFO: execute[Set the default Java version to 7.2.3.3-r1] ran successfully
[2016-07-22T11:43:30+00:00] INFO: Processing directory[/usr/lib/elasticsearch-1.4.4] action create (elasticsearch::default line 55)
[2016-07-22T11:43:30+00:00] INFO: Processing directory[/var/log/elasticsearch] action create (elasticsearch::default line 62)
[2016-07-22T11:43:30+00:00] INFO: Processing directory[/var/lib/elasticsearch] action create (elasticsearch::default line 62)
[2016-07-22T11:43:30+00:00] INFO: Processing directory[/var/run/elasticsearch] action create (elasticsearch::default line 62)
[2016-07-22T11:43:30+00:00] INFO: Processing bash[unzip elasticsearch] action run (elasticsearch::default line 69)
[2016-07-22T11:43:30+00:00] INFO: Processing bash[copy elasticsearch root] action run (elasticsearch::default line 76)
[2016-07-22T11:43:30+00:00] INFO: Processing directory[/usr/lib/elasticsearch-1.4.4/plugins] action create (elasticsearch::default line 83)
[2016-07-22T11:43:30+00:00] INFO: Processing link[/usr/lib/elasticsearch] action create (elasticsearch::default line 89)
[2016-07-22T11:43:30+00:00] INFO: Processing directory[/data/elasticsearch] action create (elasticsearch::default line 93)
[2016-07-22T11:43:30+00:00] INFO: directory[/data/elasticsearch] owner changed to 61021
[2016-07-22T11:43:30+00:00] INFO: directory[/data/elasticsearch] group changed to 65533
[2016-07-22T11:43:30+00:00] INFO: Processing directory[/usr/lib/elasticsearch-1.4.4/data] action create (elasticsearch::default line 99)
[2016-07-22T11:43:30+00:00] INFO: directory[/usr/lib/elasticsearch-1.4.4/data] owner changed to 0
[2016-07-22T11:43:30+00:00] INFO: directory[/usr/lib/elasticsearch-1.4.4/data] group changed to 0
[2016-07-22T11:43:30+00:00] INFO: Processing mount[/usr/lib/elasticsearch-1.4.4/data] action mount (elasticsearch::default line 107)
[2016-07-22T11:43:30+00:00] INFO: mount[/usr/lib/elasticsearch-1.4.4/data] mounted
[2016-07-22T11:43:30+00:00] INFO: Processing template[/usr/lib/elasticsearch-1.4.4/config/logging.yml] action create (elasticsearch::default line 114)
[2016-07-22T11:43:30+00:00] INFO: Processing directory[/usr/share/elasticsearch] action create (elasticsearch::default line 119)
[2016-07-22T11:43:30+00:00] INFO: Processing template[/usr/share/elasticsearch/elasticsearch.in.sh] action create (elasticsearch::default line 126)
[2016-07-22T11:43:30+00:00] INFO: Processing template[/usr/lib/elasticsearch-1.4.4/config/elasticsearch.yml] action create (elasticsearch::default line 137)
[2016-07-22T11:43:30+00:00] INFO: Processing template[/etc/monit.d/elasticsearch_live.monitrc] action create (elasticsearch::default line 155)
[2016-07-22T11:43:30+00:00] INFO: Processing execute[monit reload] action run (elasticsearch::default line 164)
[2016-07-22T11:43:30+00:00] INFO: execute[monit reload] ran successfully
[2016-07-22T11:43:30+00:00] INFO: Processing template[/data/<application>/shared/config/elasticsearch.yml] action create (elasticsearch::default line 180)
[2016-07-22T11:43:30+00:00] INFO: file[/etc/monit.d/sidekiq_<application>.monitrc] sending run action to execute[reload-monit] (delayed)
[2016-07-22T11:43:30+00:00] INFO: Processing execute[reload-monit] action run (sidekiq::cleanup line 7)
[2016-07-22T11:43:30+00:00] INFO: execute[reload-monit] ran successfully
[2016-07-22T11:43:30+00:00] INFO: template[/etc/monit.d/sidekiq_<application>.monitrc] sending run action to execute[restart-sidekiq-for-<application>] (delayed)
[2016-07-22T11:43:30+00:00] INFO: Processing execute[restart-sidekiq-for-<application>] action run (sidekiq::setup line 22)
[2016-07-22T11:43:31+00:00] ERROR: Running exception handlers
[2016-07-22T11:43:31+00:00] ERROR: Exception handlers complete
[2016-07-22T11:43:32+00:00] FATAL: Stacktrace dumped to /etc/chef-custom/recipes/chef-stacktrace.out
[2016-07-22T11:43:32+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[restart-sidekiq-for-<application>] (sidekiq::setup line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of monit reload && sleep 1 && monit restart all -g <application>_sidekiq ----
STDOUT: 
STDERR: Reinitializing monit daemon
monit: Cannot connect to the monit daemon. Did you start it with http support?
monit: Cannot connect to the monit daemon. Did you start it with http support?
---- End output of monit reload && sleep 1 && monit restart all -g <application>_sidekiq ----
Ran monit reload && sleep 1 && monit restart all -g <application>_sidekiq returned 1
```

How to fix it ?

**Comment by radamanthus** [comment]
Hello. Sorry for the late response here. Are you still seeing the issue? If so, can you open a support ticket so that we can take a closer look at the instance? Thanks!

**Comment by khacluan** [comment]
@radamanthus Thanks for reply, I have received the support from EY tech team
I have to increase sleep time from 1 to 40 second
```
monit reload && sleep 40 && monit restart all -g <application>_sidekiq
```
