### ISSUE TITLE
Chef run fails with "nginx.logrotate" is not a valid `source` parameter for remote_file. 

### ISSUE THREAD

**Issue by sankara** [engineyard/ey-cloud-recipes#317]
```
Digest::Digest is deprecated; use Digest
Digest::Digest is deprecated; use Digest
[0m
================================================================================[0m
[31mRecipe Compile Error in /etc/chef/recipes/cookbooks/ey-init/recipes/main.rb[0m
================================================================================[0m

[0mChef::Exceptions::InvalidRemoteFileURI[0m
--------------------------------------[0m
"nginx.logrotate" is not a valid `source` parameter for remote_file. `source` must be an absolute URI or an array of URIs.[0m

[0mCookbook Trace:[0m
---------------[0m
  /etc/chef/recipes/cookbooks/logrotate/recipes/default.rb:7:in `block in from_file'
[0m  /etc/chef/recipes/cookbooks/logrotate/recipes/default.rb:6:in `from_file'
[0m  /etc/chef/recipes/cookbooks/ey-core/recipes/default.rb:16:in `from_file'
[0m  /etc/chef/recipes/cookbooks/ey-init/recipes/main.rb:16:in `from_file'[0m

[0mRelevant File Content:[0m
----------------------[0m
/etc/chef/recipes/cookbooks/logrotate/recipes/default.rb:
[0m
[0m  1:  #
[0m  2:  # Cookbook Name:: logrotate
[0m  3:  # Recipe:: default
[0m  4:  #
[0m  5:  
[0m  6:  remote_file "/etc/logrotate.d/nginx" do
[0m  7>>   source "nginx.logrotate"
[0m  8:    owner "root"
[0m  9:    group "root"
[0m 10:    mode "0644"
[0m 11:    backup 0
[0m 12:  end
[0m 13:  
[0m 14:  cron "logrotate -f /etc/logrotate.d/nginx" do
[0m 15:    minute  '0'
[0m 16:    command "logrotate -f /etc/logrotate.d/nginx"
[0m
[0mPlatform:[0m
---------[0m
x86_64-linux[0m
```

**Comment by RajRoR** [comment]
Did you find the fix?
